### ISSUE TITLE
allow presets for field configurations

### ISSUE THREAD

**Issue by outoftime** [brewster/elastictastic#13]
It would be helpful to be able to configure preset field configurations (with a certain type, analyzer, etc.):

``` yml
presets:
  my_preset:
    type: string
    store: yes
    analyzer: whitespace
    omit_norms: true
```

And then just refer to them like so:

``` ruby
field :my_field, :preset => :my_preset
```
